# Generated by Django 4.2.5 on 2023-09-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0011_alter_look_and_feel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='feature_image',
            field=models.FileField(upload_to='events'),
        ),
    ]
